### PR TITLE
Add linting checks to find explores and fields which lack descriptions (#88)

### PR DESCRIPTION
**Pull request by AdamBethke**
Adds a set of checks in the same style as lint_labels; the two checks test whether there are non-hidden fields which are missing descriptions, and whether there are explores missing descriptions.

To do this work, this adds another property to the Explore class (description), which surfaces this parameter from the explore model.

### CODE REVIEW

**Comment by ryantuck** [comment]
Hey @AdamBethke sorry for the delay here! I'd love to get some eyes on this in the next few days or so. Will keep you posted, but otherwise the code honestly looks great on first read!

**Comment by AdamBethke** [comment]
Awesome! No worries, totally get it takes time and there are probably much more pressing things going on. Thanks again for considering it!

**Comment by AdamBethke** [comment]
One note is that it looks like it works with the `--json` flag, but the fields are missing on the non-json version. I'm looking into it, but wanted to flag it here

**Comment by ryantuck** [comment]
Hey @AdamBethke -- wanted to give you an update here. We've been discussing internally how to best prioritize triaging external contributions to lookmlint, and came to the agreement that our team and organization at large don't have the bandwidth or structures in-place to support an open source project like we would need to. As a result, we'll be archiving this repo and no longer actively maintaining it.

I appreciate you contributing here, and our product manager loved your suggestion for requiring descriptions on explores. At this point, go forth and use your fork of the repo for your lookml projects. If you wanna chat about this further, feel free to shoot me an email!

**Pull request closed without merging**
